"""
Database schema for the cert-prep platform, using SQLModel (Pydantic +
SQLAlchemy in one place). Field names mirror the Pydantic models in
gemini_integration_example.py so data coming back from Gemini maps
directly onto these tables.

THE FIX this schema exists to make: analyze_weak_spots() was guessing
gap_level from the concept name alone, because the toy answer_history
list didn't carry question_type. Here, question_type is set once on
Question at generation time, and Attempt only stores which question was
answered — get_answer_history_for_user() below joins them, so the real
question_type is always available, never guessed.

Setup:
    pip install sqlmodel --break-system-packages
"""

import random
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from sqlmodel import JSON, Column, Field, Relationship, Session, SQLModel, create_engine, select


class QuestionType(str, Enum):
    conceptual = "conceptual"
    detail_recall = "detail_recall"


class Difficulty(str, Enum):
    easy = "easy"
    medium = "medium"
    hard = "hard"


class ReviewStatus(str, Enum):
    """Questions are AI-generated offline into a bank, then reviewed before
    users ever see them. This exists because prompt instructions alone
    don't guarantee factual accuracy — two separate hallucinations showed
    up during development, one of them contradicting a correct value the
    same model had produced two calls earlier. Human review is the
    structural answer; only `approved` questions get served."""
    pending = "pending"
    approved = "approved"
    rejected = "rejected"


# The four SAA-C03 exam domains. `domain` used to be free text on both entry
# paths, and the generator filled it with service categories of its own
# invention ("Storage", "Messaging") plus two spellings of "Networking and
# Content Delivery" — 12 distinct values for 4 domains. It is user-visible as
# the badge in the quiz, and it is what any weighting against the exam
# blueprint has to group by.
EXAM_DOMAINS = (
    "Design Secure Architectures",
    "Design Resilient Architectures",
    "Design High-Performing Architectures",
    "Design Cost-Optimized Architectures",
)


def tag_key(tag: str) -> str:
    """Equivalence key for a concept tag: lowercase, last word singularised.

    `concept_tags` is load-bearing — `select_next_question()` prefers questions
    tagged with a user's weak concepts and `analyze_weak_spots` reasons over the
    same strings — so `Caching Strategies` and `caching strategies` being
    distinct concepts to the code costs real adaptivity, silently and with no
    error. This key is what lets a new tag be recognised as one the bank
    already has."""
    words = tag.lower().split()
    if words:
        last = words[-1]
        if last.endswith("ies"):
            words[-1] = last[:-3] + "y"
        elif last.endswith("s") and not last.endswith("ss"):
            words[-1] = last[:-1]
    return " ".join(words)


def canonical_tags(tags: list[str], known: list[str]) -> list[str]:
    """Rewrite tags to the spelling the bank already uses, preserving order
    and dropping duplicates the rewrite creates. Only collapses variants of
    the same string; tags at different granularity ("visibility timeout" vs
    "SQS visibility timeout") are left alone, since merging those is a
    judgement about meaning rather than spelling."""
    by_key = {tag_key(t): t for t in known}
    out, seen = [], set()
    for tag in tags:
        canonical = by_key.get(tag_key(tag), tag)
        if canonical not in seen:
            seen.add(canonical)
            out.append(canonical)
    return out


class User(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    email: str = Field(unique=True, index=True)
    target_certification: Optional[str] = None
    exam_date: Optional[str] = None  # ISO date string, e.g. "2026-11-15"
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None))

    attempts: list["Attempt"] = Relationship(back_populates="user")
    study_plans: list["StudyPlan"] = Relationship(back_populates="user")


class Question(SQLModel, table=True):
    """A question generated by prompt #1, cached so it isn't regenerated
    on every view and so its question_type survives to inform later
    weak-spot analysis."""
    id: Optional[int] = Field(default=None, primary_key=True)
    certification: str = Field(index=True)
    domain: str
    question_text: str
    options: list[str] = Field(sa_column=Column(JSON))
    correct_index: int
    explanation: str
    concept_tags: list[str] = Field(sa_column=Column(JSON))
    question_type: QuestionType
    difficulty: Difficulty
    review_status: ReviewStatus = Field(default=ReviewStatus.pending, index=True)
    review_note: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None))

    attempts: list["Attempt"] = Relationship(back_populates="question")
    reports: list["QuestionReport"] = Relationship(back_populates="question")
    sources: list["QuestionSource"] = Relationship(back_populates="question")
    option_explanations: list["OptionExplanation"] = Relationship(back_populates="question")


class Attempt(SQLModel, table=True):
    """One user answering one question. Correctness and question_type are
    NOT duplicated here — they're derived by joining to Question, so
    there's exactly one source of truth for each."""
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id", index=True)
    question_id: int = Field(foreign_key="question.id", index=True)
    selected_index: int
    answered_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None))

    user: User = Relationship(back_populates="attempts")
    question: Question = Relationship(back_populates="attempts")

    @property
    def is_correct(self) -> bool:
        return self.selected_index == self.question.correct_index


class ReportReason(str, Enum):
    """What the user is claiming is wrong. Kept coarse on purpose: a long
    menu makes people pick the first plausible entry, and the free-text
    field is where the useful detail actually is."""
    wrong_answer = "wrong_answer"
    outdated = "outdated"
    ambiguous = "ambiguous"
    typo = "typo"
    other = "other"


class QuestionReport(SQLModel, table=True):
    """A user flagging a question as wrong, stale or ambiguous.

    A separate table, not a column on Question, for two reasons. The
    modelling one: a report is an event — several users can flag the same
    question, and each report has its own reason and moment — so it isn't
    an attribute of the question. The practical one: this project has no
    migrations, and the documented workaround for a schema change is
    deleting cert_prep.db. `create_all` adds a missing table without
    touching existing ones, so a new table costs nothing, while a new
    column on Question would have meant destroying the bank.

    This closes the gap the accuracy notes flag: review catches what a
    reviewer notices, and a candidate studying a topic in depth will
    notice things a reviewer didn't."""
    id: Optional[int] = Field(default=None, primary_key=True)
    question_id: int = Field(foreign_key="question.id", index=True)
    # Nullable so a report never depends on knowing who sent it. The
    # signal is about the question, not the reporter.
    user_id: Optional[int] = Field(default=None, foreign_key="user.id", index=True)
    reason: ReportReason
    detail: Optional[str] = None
    resolved: bool = Field(default=False, index=True)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None))

    question: Question = Relationship(back_populates="reports")


class OptionExplanation(SQLModel, table=True):
    """Why one specific option is right or wrong, one row per option.

    The stored `explanation` is a single text covering the correct answer and
    every distractor. That is the right thing for a reviewer to read, and the
    wrong thing to show a candidate who picked D and now has to find the one
    paragraph about D in a wall about B and C as well. These rows let the
    quiz show exactly two things: why the pick was wrong, and why the correct
    one is right.

    A separate table, like QuestionSource and QuestionReport: no migrations
    here, and `create_all` adds a table without touching Question. Optional
    per question — the API falls back to the full explanation when a
    question has no rows, so older content keeps working."""
    id: Optional[int] = Field(default=None, primary_key=True)
    question_id: int = Field(foreign_key="question.id", index=True)
    option_index: int
    text: str

    question: Question = Relationship(back_populates="option_explanations")


class QuestionSource(SQLModel, table=True):
    """A documentation page a question's claims were checked against.

    Hand-written batches carry a `sources` array per question, and the
    importer used to drop it — which meant the reviewer, the one person who
    has to decide whether a specific threshold is real, was the only one who
    couldn't see what it had been checked against. Storing it makes a batch
    checkable instead of merely plausible.

    A separate table for the same reason as QuestionReport: this project has
    no migrations, and `create_all` adds a missing table without touching
    existing ones, whereas a new column on Question would have meant deleting
    cert_prep.db and the questions in it."""
    id: Optional[int] = Field(default=None, primary_key=True)
    question_id: int = Field(foreign_key="question.id", index=True)
    url: str

    question: Question = Relationship(back_populates="sources")


class WeakSpotSnapshot(SQLModel, table=True):
    """A weak-spot analysis, kept so the same history isn't analysed twice.

    The analysis is a live model call — the only one left in the user flow —
    and it is a pure function of the user's answer history. Without this,
    every visit to /weak-spots spent one of twenty daily requests to
    recompute an unchanged answer, and a page refresh cost as much as
    generating a question. Keyed on the attempt count: a new answer changes
    the history, so it changes the key, and the next visit recomputes."""
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id", index=True)
    attempt_count: int
    analysis: dict = Field(sa_column=Column(JSON))
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None))


class StudyPlan(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id", index=True)
    exam_date: str
    feasible: bool
    warning: Optional[str] = None
    weekly_plan: list[dict] = Field(sa_column=Column(JSON))
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None))

    user: User = Relationship(back_populates="study_plans")


# ---------------------------------------------------------------------
# Engine — SQLite for local dev, swap the URL for Postgres in production
# ---------------------------------------------------------------------

engine = create_engine("sqlite:///cert_prep.db", echo=False)


def create_db_and_tables():
    SQLModel.metadata.create_all(engine)


# ---------------------------------------------------------------------
# THE FIX: build answer_history for analyze_weak_spots() from real data.
# This replaces the toy answer_history list in the demo at the bottom
# of gemini_integration_example.py.
# ---------------------------------------------------------------------

def get_answer_history_for_user(session: Session, user_id: int) -> list[dict]:
    """Returns the shape analyze_weak_spots() expects. Every entry's
    question_type comes from the actual Question row via the join —
    never inferred from the concept string."""
    statement = select(Attempt).where(Attempt.user_id == user_id)
    attempts = session.exec(statement).all()

    now = datetime.now(timezone.utc).replace(tzinfo=None)
    history = []
    for attempt in attempts:
        question = attempt.question
        for concept in question.concept_tags:
            history.append({
                "concept": concept,
                "correct": attempt.is_correct,
                "days_ago": (now - attempt.answered_at).days,
                "question_type": question.question_type.value,
            })
    return history


# ---------------------------------------------------------------------
# Question selection — this is where adaptivity now lives. It moved out
# of generation (which is offline and batched) into selection, which is
# per-user and instant. Same value to the user, no API call.
# ---------------------------------------------------------------------

def select_next_question(
    session: Session,
    user_id: int,
    certification: str,
    weak_concepts: Optional[list[str]] = None,
) -> Optional[Question]:
    """Pick the next question for a user from the approved bank.

    Rules, in order:
      1. Only approved questions for this certification.
      2. Never repeat one the user has already answered.
      3. Prefer questions tagged with the user's weak concepts.
    Returns None when the bank is exhausted for this user."""
    answered_ids = {
        a.question_id
        for a in session.exec(select(Attempt).where(Attempt.user_id == user_id)).all()
    }

    statement = select(Question).where(
        Question.certification == certification,
        Question.review_status == ReviewStatus.approved,
    )
    candidates = [q for q in session.exec(statement).all() if q.id not in answered_ids]
    if not candidates:
        return None

    if weak_concepts:
        weak = set(weak_concepts)
        targeted = [q for q in candidates if weak & set(q.concept_tags)]
        if targeted:
            candidates = targeted

    return random.choice(candidates)


# ---------------------------------------------------------------------
# Demo: create tables, insert one user/question/attempt, show the
# corrected answer_history output
# ---------------------------------------------------------------------

if __name__ == "__main__":
    create_db_and_tables()

    with Session(engine) as session:
        user = User(email="test@example.com", target_certification="AWS ANS-C01", exam_date="2026-11-15")
        session.add(user)
        session.commit()
        session.refresh(user)

        question = Question(
            certification="AWS Advanced Networking Specialty (ANS-C01)",
            domain="Hybrid Connectivity",
            question_text="Which BGP community sets High Local Preference on a Transit VIF?",
            options=["7224:7300", "7224:7100", "7224:9300", "7224:8200"],
            correct_index=0,
            explanation="7224:7300 sets High Local Preference for Private/Transit VIF routing.",
            concept_tags=["Transit Gateway route propagation", "BGP community tags"],
            question_type=QuestionType.detail_recall,
            difficulty=Difficulty.hard,
        )
        session.add(question)
        session.commit()
        session.refresh(question)

        attempt = Attempt(user_id=user.id, question_id=question.id, selected_index=2)  # wrong answer
        session.add(attempt)
        session.commit()

        history = get_answer_history_for_user(session, user.id)
        print("=== answer_history built from real data (not guessed) ===")
        for entry in history:
            print(entry)