"""baseline: schema as of 2026-09-22

The schema as it stood when Alembic was introduced, generated from the
models against an empty database. Databases that already existed at that
point — the dev SQLite file and the Neon production database, both built
by SQLModel's create_all — were marked as already at this revision with
`alembic stamp head` rather than having it run against them. So this
migration only ever executes on a database created from scratch.

Revision ID: 95efe19f5ef4
Revises: 
Create Date: 2026-09-22 14:29:49.906048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95efe19f5ef4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('concept_tags', sa.JSON(), nullable=True),
    sa.Column('question_type', sa.Enum('conceptual', 'detail_recall', name='questiontype'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'rejected', name='reviewstatus'), nullable=False),
    sa.Column('review_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_certification'), ['certification'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_review_status'), ['review_status'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_certification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exam_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_user_id'), ['user_id'], unique=False)

    op.create_table('optionexplanation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optionexplanation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optionexplanation_question_id'), ['question_id'], unique=False)

    op.create_table('questionreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Enum('wrong_answer', 'outdated', 'ambiguous', 'typo', 'other', name='reportreason'), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questionreport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionreport_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionreport_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionreport_user_id'), ['user_id'], unique=False)

    op.create_table('questionsource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questionsource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionsource_question_id'), ['question_id'], unique=False)

    op.create_table('studyplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feasible', sa.Boolean(), nullable=False),
    sa.Column('warning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weekly_plan', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studyplan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studyplan_user_id'), ['user_id'], unique=False)

    op.create_table('weakspotsnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weakspotsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weakspotsnapshot_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weakspotsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weakspotsnapshot_user_id'))

    op.drop_table('weakspotsnapshot')
    with op.batch_alter_table('studyplan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studyplan_user_id'))

    op.drop_table('studyplan')
    with op.batch_alter_table('questionsource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionsource_question_id'))

    op.drop_table('questionsource')
    with op.batch_alter_table('questionreport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionreport_user_id'))
        batch_op.drop_index(batch_op.f('ix_questionreport_resolved'))
        batch_op.drop_index(batch_op.f('ix_questionreport_question_id'))

    op.drop_table('questionreport')
    with op.batch_alter_table('optionexplanation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optionexplanation_question_id'))

    op.drop_table('optionexplanation')
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_question_id'))

    op.drop_table('attempt')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_review_status'))
        batch_op.drop_index(batch_op.f('ix_question_certification'))

    op.drop_table('question')
    # ### end Alembic commands ###
